# -- Override full name
fullnameOverride: ""
# -- Override name
nameOverride: ""

# -- Replica count
replicaCount: 1

image:
  # -- Image repository
  repository: ghcr.io/sap/component-operator
  # -- Image tag (defauls to .Chart.AppVersion)
  tag: ""
  # -- Image pull policy
  pullPolicy: IfNotPresent

# -- Image pull secrets
imagePullSecrets: []

# -- Additional pod labels
podLabels: {}

# -- Additional pod annotations
podAnnotations: {}

# -- Node selector
nodeSelector: {}

# -- Affinity settings
affinity: {}

# -- Topology spread constraints (if unspecified, default constraints for hostname and zone will be generated)
topologySpreadConstraints: []

# -- Default topology spread policy for hostname
defaultHostNameSpreadPolicy: ScheduleAnyway

# -- Default topology spread policy for zone
defaultZoneSpreadPolicy: ScheduleAnyway

# -- Tolerations
tolerations: []

# -- Priority class
priorityClassName: ""

# -- Pod security context
podSecurityContext: {}

# -- Container security context
securityContext: {}

resources:
  limits:
    # -- CPU limit
    cpu: 100m
    # -- Memory limit
    memory: 128Mi
  requests:
    # -- CPU request
    cpu: 100m
    # -- Memory request
    memory: 128Mi

pdb:
  # -- Whether to create a PodDisruptionBudget for the webhook
  enabled: true
  # -- Labels to set on the PodDisruptionBudget
  labels: {}
  # -- Annotations to set on the PodDisruptionBudget
  annotations: {}
  # -- Number of pods that are available after eviction as number or percentage (e.g. 50%)
  # @default -- `"1"` (defaults to 1 if not specified)
  minAvailable: "1"
  # -- Number of pods that are unavailable after eviction as number or percentage (e.g: 50%); has higher precedence over `pdb.minAvailable`
  maxUnavailable: ""

# -- Controller options
options: {}